source_site:

    site_name: source_site_example_name
    site_number: source_site_example_number
    site_region: source_site_example_region

application_targets:

   -  name: Google
      host_target: www.google.com
      host_target_port: 80
      ssl: False
      request_file: http_get_google_example.txt
      interval_timer : 60
      log_level : Informational
      log_output_file : app1_log_output
      max_log_size : 50000
      max_connection_thread_count : 20

   -  name: HP
      host_target: www.hp.com
      host_target_port: 443
      ssl: True
      request_file: http_get_hp_example.txt
      interval_timer : 60
      log_level : Informational
      log_output_file : app2_log_output
      max_log_size : 50000
      max_connection_thread_count : 20

